import React, { createContext, useContext, useState, useEffect } from "react";

// ── Translations ──────────────────────────────────────────────
export const TRANSLATIONS = {
    english: {
        dashboard: "Dashboard",
        explore: "My Bookings",
        notifications: "Notifications",
        favorites: "Favorites",
        settings: "Settings",
        findYourStay: "Find Your Stay",
        checkIn: "CHECK IN",
        checkOut: "CHECK OUT",
        whereTo: "WHERE TO",
        guests: "GUESTS",
        search: "Search",
        availableLodging: "Available Lodging",
        viewAll: "View all",
        mostPopular: "Most Popular",
        specialOffers: "Special Offers",
        nearMe: "Near Me",
        bookNow: "Book Now",
        limitedTimeOffer: "Limited Time Offer",
        limitedOfferText: "Book now and save up to 45% on selected hotels this season.",
        location: "Location",
        overview: "Overview",
        facilities: "Facilities",
        details: "Details",
        reviews: "Reviews",
        readMore: "Read more",
        showLess: "Show less",
        bookingSummary: "Booking Summary",
        confirmPay: "Confirm & Pay",
        duration: "DURATION",
        nights: "nights",
        night: "night",
        taxesFees: "Taxes & fees",
        total: "Total",
    },
    greek: {
        dashboard: "Αρχική",
        explore: "Κρατήσεις μου",
        notifications: "Ειδοποιήσεις",
        favorites: "Αγαπημένα",
        settings: "Ρυθμίσεις",
        findYourStay: "Βρες το Ξενοδοχείο σου",
        checkIn: "CHECK IN",
        checkOut: "CHECK OUT",
        whereTo: "ΠΡΟΟΡΙΣΜΟΣ",
        guests: "ΕΠΙΣΚΕΠΤΕΣ",
        search: "Αναζήτηση",
        availableLodging: "Διαθέσιμα Καταλύματα",
        viewAll: "Όλα",
        mostPopular: "Πιο Δημοφιλή",
        specialOffers: "Προσφορές",
        nearMe: "Κοντά μου",
        bookNow: "Κράτηση",
        limitedTimeOffer: "Περιορισμένη Προσφορά",
        limitedOfferText: "Κλείστε τώρα και εξοικονομήστε έως 45% σε επιλεγμένα ξενοδοχεία.",
        location: "Τοποθεσία",
        overview: "Επισκόπηση",
        facilities: "Παροχές",
        details: "Λεπτομέρειες",
        reviews: "Κριτικές",
        readMore: "Περισσότερα",
        showLess: "Λιγότερα",
        bookingSummary: "Σύνοψη Κράτησης",
        confirmPay: "Επιβεβαίωση & Πληρωμή",
        duration: "ΔΙΑΡΚΕΙΑ",
        nights: "νύχτες",
        night: "νύχτα",
        taxesFees: "Φόροι & Τέλη",
        total: "Σύνολο",
    },
    spanish: {
        dashboard: "Inicio",
        explore: "Mis Reservas",
        notifications: "Notificaciones",
        favorites: "Favoritos",
        settings: "Ajustes",
        findYourStay: "Encuentra tu Alojamiento",
        checkIn: "ENTRADA",
        checkOut: "SALIDA",
        whereTo: "DESTINO",
        guests: "HUÉSPEDES",
        search: "Buscar",
        availableLodging: "Alojamientos Disponibles",
        viewAll: "Ver todo",
        mostPopular: "Más Popular",
        specialOffers: "Ofertas Especiales",
        nearMe: "Cerca de mí",
        bookNow: "Reservar",
        limitedTimeOffer: "Oferta por Tiempo Limitado",
        limitedOfferText: "Reserva ahora y ahorra hasta un 45% en hoteles seleccionados.",
        location: "Ubicación",
        overview: "Resumen",
        facilities: "Instalaciones",
        details: "Detalles",
        reviews: "Reseñas",
        readMore: "Leer más",
        showLess: "Menos",
        bookingSummary: "Resumen de Reserva",
        confirmPay: "Confirmar y Pagar",
        duration: "DURACIÓN",
        nights: "noches",
        night: "noche",
        taxesFees: "Impuestos y tasas",
        total: "Total",
    },
    french: {
        dashboard: "Accueil",
        explore: "Mes Réservations",
        notifications: "Notifications",
        favorites: "Favoris",
        settings: "Paramètres",
        findYourStay: "Trouvez votre Séjour",
        checkIn: "ARRIVÉE",
        checkOut: "DÉPART",
        whereTo: "DESTINATION",
        guests: "VOYAGEURS",
        search: "Rechercher",
        availableLodging: "Hébergements Disponibles",
        viewAll: "Voir tout",
        mostPopular: "Plus Populaires",
        specialOffers: "Offres Spéciales",
        nearMe: "Près de moi",
        bookNow: "Réserver",
        limitedTimeOffer: "Offre Limitée",
        limitedOfferText: "Réservez maintenant et économisez jusqu'à 45% sur des hôtels sélectionnés.",
        location: "Localisation",
        overview: "Aperçu",
        facilities: "Équipements",
        details: "Détails",
        reviews: "Avis",
        readMore: "Lire plus",
        showLess: "Moins",
        bookingSummary: "Récapitulatif",
        confirmPay: "Confirmer et Payer",
        duration: "DURÉE",
        nights: "nuits",
        night: "nuit",
        taxesFees: "Taxes et frais",
        total: "Total",
    },
    german: {
        dashboard: "Startseite",
        explore: "Meine Buchungen",
        notifications: "Benachrichtigungen",
        favorites: "Favoriten",
        settings: "Einstellungen",
        findYourStay: "Finde dein Hotel",
        checkIn: "ANREISE",
        checkOut: "ABREISE",
        whereTo: "ZIEL",
        guests: "GÄSTE",
        search: "Suchen",
        availableLodging: "Verfügbare Unterkünfte",
        viewAll: "Alle anzeigen",
        mostPopular: "Beliebteste",
        specialOffers: "Sonderangebote",
        nearMe: "In der Nähe",
        bookNow: "Buchen",
        limitedTimeOffer: "Zeitlich begrenztes Angebot",
        limitedOfferText: "Jetzt buchen und bis zu 45% bei ausgewählten Hotels sparen.",
        location: "Standort",
        overview: "Übersicht",
        facilities: "Ausstattung",
        details: "Details",
        reviews: "Bewertungen",
        readMore: "Mehr lesen",
        showLess: "Weniger",
        bookingSummary: "Buchungsübersicht",
        confirmPay: "Bestätigen & Bezahlen",
        duration: "DAUER",
        nights: "Nächte",
        night: "Nacht",
        taxesFees: "Steuern & Gebühren",
        total: "Gesamt",
    },
    japanese: {
        dashboard: "ホーム",
        explore: "予約一覧",
        notifications: "通知",
        favorites: "お気に入り",
        settings: "設定",
        findYourStay: "ホテルを探す",
        checkIn: "チェックイン",
        checkOut: "チェックアウト",
        whereTo: "目的地",
        guests: "ゲスト",
        search: "検索",
        availableLodging: "利用可能な宿泊施設",
        viewAll: "すべて見る",
        mostPopular: "人気",
        specialOffers: "特別オファー",
        nearMe: "近く",
        bookNow: "予約する",
        limitedTimeOffer: "期間限定オファー",
        limitedOfferText: "今すぐ予約して最大45%割引。",
        location: "場所",
        overview: "概要",
        facilities: "設備",
        details: "詳細",
        reviews: "レビュー",
        readMore: "続きを読む",
        showLess: "閉じる",
        bookingSummary: "予約概要",
        confirmPay: "確認・支払い",
        duration: "期間",
        nights: "泊",
        night: "泊",
        taxesFees: "税金・手数料",
        total: "合計",
    },
};

// ── Context ───────────────────────────────────────────────────
const SettingsContext = createContext(null);

export const SettingsProvider = ({ children }) => {
    const [language, setLanguage] = useState("english");
    const [darkMode, setDarkMode] = useState(true);

    // Apply dark/light mode to <html>
    useEffect(() => {
        document.documentElement.setAttribute("data-theme", darkMode ? "dark" : "light");
    }, [darkMode]);

    const t = (key) => (TRANSLATIONS[language] || TRANSLATIONS.english)[key] || key;

    return ( <
        SettingsContext.Provider value = {
            { language, setLanguage, darkMode, setDarkMode, t } } > { children } <
        /SettingsContext.Provider>
    );
};

export const useSettings = () => useContext(SettingsContext);